version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "credio-institucional-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pddlqtg9k50a"
s3_prefix = "credio-institucional-serverless"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
